apiVersion: v1
 
kind: PersistentVolumeClaim
 
metadata:
 
  name: jenkins-pvc
 
  annotations:
 
    volume.beta.kubernetes.io/storage-class: "ibmc-file-bronze"
 
  labels:
 
    billingType: "hourly"
 
spec:
 
  accessModes:
 
    - ReadWriteMany
 
  resources:
 
    requests:
 
      storage: 20Gi
