apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: pgbackend
  namespace: serverless-console
spec:
  serviceName: pgbackend
  replicas: 1
  template:
    metadata:
      labels:
        app: pgbackend
    spec:
      securityContext:
        fsGroup: 26
      containers:
      - name: pgbackend
        image: crunchydata/crunchy-postgres:centos7-10.0-1.6.0
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: PG_PRIMARY_USER
          value: primaryuser
        - name: PGHOST
          value: /tmp
        - name: PG_MODE
          value: set
        - name: PG_PRIMARY_PASSWORD
          value: password
        - name: PG_USER
          value: testuser
        - name: PG_PASSWORD
          value: password
        - name: PG_DATABASE
          value: userdb
        - name: PG_ROOT_PASSWORD
          value: password
        - name: PG_PRIMARY_PORT
          value: "5432"
        - name: PG_PRIMARY_HOST
          value: pgbackend-primary
        volumeMounts:
        - name: pgdata
          mountPath: /pgdata
          readOnly: false
      initContainers:
      - name: permissionsfix
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
          - chown 26:26 /mount;
        volumeMounts:
        - name: pgdata
          mountPath: /mount
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: pgdata-pgbackend-0
